# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'apigeeconfig-ci-cd'
on:
  workflow_dispatch:
  push:
    paths:
      - src/config/**
jobs:
  deploy_config:
    name: 'config'
    permissions:
      id-token: write
      contents: read
    runs-on: 'ubuntu-latest'
    steps:
    - name: Clone repo
      uses: actions/checkout@master
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
        service_account: ${{ secrets.SVC_ACCOUNT_EMAIL }}
    - name: Deploy Configuration
      run: |
        mvn install \
          -Ptest \
          -Denv="${{ secrets.APIGEE_ENV }}" \
          -Dtoken=${{ steps.auth.outputs.access_token }} \
          -Dorg="${{ secrets.APIGEE_ORG }}" \
          -Dapigee.config.options=update \
          -Dapigee.config.dir=resources/apigee
      working-directory: ./src/config
